# Generated by Django 5.1 on 2024-09-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='thumb',
            field=models.ImageField(upload_to='thumb_filmes/'),
        ),
    ]
